// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxjoQghnTqjbXDJNVMzxuZzX4EEgftKhg',
    appId: '1:270285366458:web:96e73639d1aa0c724c4e83',
    messagingSenderId: '270285366458',
    projectId: 'outcrop-67996',
    authDomain: 'outcrop-67996.firebaseapp.com',
    storageBucket: 'outcrop-67996.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRIqxvUJAsudm_1qzD5iFv3bc8-6eFV-8',
    appId: '1:270285366458:android:2d7c167f505d7d864c4e83',
    messagingSenderId: '270285366458',
    projectId: 'outcrop-67996',
    storageBucket: 'outcrop-67996.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFuV_IheLJvwNhhKJfcIakG4M1PjiTXFY',
    appId: '1:270285366458:ios:99243961d39e29014c4e83',
    messagingSenderId: '270285366458',
    projectId: 'outcrop-67996',
    storageBucket: 'outcrop-67996.firebasestorage.app',
    iosBundleId: 'com.example.outcrop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFuV_IheLJvwNhhKJfcIakG4M1PjiTXFY',
    appId: '1:270285366458:ios:99243961d39e29014c4e83',
    messagingSenderId: '270285366458',
    projectId: 'outcrop-67996',
    storageBucket: 'outcrop-67996.firebasestorage.app',
    iosBundleId: 'com.example.outcrop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxjoQghnTqjbXDJNVMzxuZzX4EEgftKhg',
    appId: '1:270285366458:web:49cde3d14fea264b4c4e83',
    messagingSenderId: '270285366458',
    projectId: 'outcrop-67996',
    authDomain: 'outcrop-67996.firebaseapp.com',
    storageBucket: 'outcrop-67996.firebasestorage.app',
  );
}
